import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Copy, Download, Check, FileJson, FileText } from "lucide-react";
import type { RichAnalyzeResult } from "@/lib/scan-types";

interface Props { result: RichAnalyzeResult }

export function ExportPanel({ result }: Props) {
  const [copied, setCopied] = useState<string | null>(null);

  function copy(text: string, key: string) {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(key);
      setTimeout(() => setCopied(null), 2000);
    });
  }

  function toMarkdown(): string {
    const r = result;
    const lines = [
      `# AlphaScout AI — ${r.type.toUpperCase()} Analysis Report`,
      `**Target:** \`${r.target}\``,
      `**Chain:** ${r.chain ?? "N/A"}`,
      `**Risk Score:** ${r.riskScore ?? "N/A"}/100`,
      `**Analyzed:** ${new Date(r.analyzedAt).toLocaleString()}`,
      "",
      "## Summary",
      r.summary,
      "",
    ];

    if (r.insights.length) {
      lines.push("## Key Insights", ...r.insights.map((i) => `- ${i}`), "");
    }
    if (r.recommendations.length) {
      lines.push("## Recommendations", ...r.recommendations.map((i) => `- ${i}`), "");
    }

    if (r.walletScan) {
      const w = r.walletScan;
      lines.push(
        "## Wallet Data",
        `- Portfolio Value: ${w.totalNetWorthUsd != null ? `$${w.totalNetWorthUsd.toLocaleString()}` : "N/A"}`,
        `- Native Balance: ${w.nativeBalance} ${w.nativeSymbol}`,
        `- Transactions: ${w.txCount}`,
        `- Wallet Age: ${w.walletAgeDays != null ? `${w.walletAgeDays} days` : "N/A"}`,
        `- Tokens: ${w.tokens.length}`,
        `- NFTs: ${w.nfts.length}`,
        `- DeFi Positions: ${w.defiPositions.length}`,
        `- Smart Money Score: ${w.smartMoneyScore ?? "N/A"}`,
        `- Wallet Health Score: ${w.walletHealthScore ?? "N/A"}`,
        "",
      );
    }

    if (r.tokenScan) {
      const t = r.tokenScan;
      lines.push(
        "## Token Data",
        `- Symbol: ${t.symbol} (${t.name})`,
        `- Price: ${t.priceUsd != null ? `$${t.priceUsd}` : "N/A"}`,
        `- Market Cap: ${t.marketCapUsd != null ? `$${t.marketCapUsd.toLocaleString()}` : "N/A"}`,
        `- Liquidity: ${t.liquidityUsd != null ? `$${t.liquidityUsd.toLocaleString()}` : "N/A"}`,
        `- Security Risk: ${t.security.overallRisk.toUpperCase()}`,
        `- Honeypot: ${t.security.isHoneypot === null ? "Unknown" : t.security.isHoneypot ? "YES" : "No"}`,
        `- Buy Tax: ${t.security.buyTax ?? "?"}%`,
        `- Sell Tax: ${t.security.sellTax ?? "?"}%`,
        "",
      );
    }

    lines.push("---", "*Generated by AlphaScout AI — alphascout.ai*");
    return lines.join("\n");
  }

  function toJSON(): string {
    return JSON.stringify(result, null, 2);
  }

  function toPlainText(): string {
    const r = result;
    return [
      `ALPHASCOUT AI — ${r.type.toUpperCase()} ANALYSIS`,
      `Target: ${r.target}`,
      `Risk Score: ${r.riskScore ?? "N/A"}/100`,
      `Summary: ${r.summary}`,
      "",
      r.insights.length ? `Insights:\n${r.insights.map((i) => `  • ${i}`).join("\n")}` : "",
      r.recommendations.length ? `\nRecommendations:\n${r.recommendations.map((i) => `  → ${i}`).join("\n")}` : "",
    ].filter(Boolean).join("\n");
  }

  return (
    <div className="flex flex-wrap items-center gap-2">
      <span className="text-xs font-mono text-muted-foreground/60">Export:</span>

      <Button
        variant="outline"
        size="sm"
        className="gap-1.5 text-xs font-mono h-7 border-border/40 hover:border-primary/40"
        onClick={() => copy(toPlainText(), "text")}
      >
        {copied === "text" ? <Check className="h-3 w-3 text-success" /> : <Copy className="h-3 w-3" />}
        Copy Report
      </Button>

      <Button
        variant="outline"
        size="sm"
        className="gap-1.5 text-xs font-mono h-7 border-border/40 hover:border-primary/40"
        onClick={() => copy(toMarkdown(), "md")}
      >
        {copied === "md" ? <Check className="h-3 w-3 text-success" /> : <FileText className="h-3 w-3" />}
        Markdown
      </Button>

      <Button
        variant="outline"
        size="sm"
        className="gap-1.5 text-xs font-mono h-7 border-border/40 hover:border-primary/40"
        onClick={() => copy(toJSON(), "json")}
      >
        {copied === "json" ? <Check className="h-3 w-3 text-success" /> : <FileJson className="h-3 w-3" />}
        JSON
      </Button>

      <Button
        variant="outline"
        size="sm"
        className="gap-1.5 text-xs font-mono h-7 border-border/40 hover:border-primary/40"
        onClick={() => {
          const blob = new Blob([toMarkdown()], { type: "text/markdown" });
          const url = URL.createObjectURL(blob);
          const a = document.createElement("a");
          a.href = url;
          a.download = `alphascout-${result.type}-${result.target.slice(0, 12)}.md`;
          a.click();
          URL.revokeObjectURL(url);
        }}
      >
        <Download className="h-3 w-3" />
        Download
      </Button>
    </div>
  );
}
