import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Copy, Download, Check, FileJson, FileText, Printer } from "lucide-react";
import type { RichAnalyzeResult } from "@/lib/scan-types";
import { ShareButton } from "./share-button";

interface Props { result: RichAnalyzeResult }

export function ExportPanel({ result }: Props) {
  const [copied, setCopied] = useState<string | null>(null);

  function copy(text: string, key: string) {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(key);
      setTimeout(() => setCopied(null), 2000);
    });
  }

  function toMarkdown(): string {
    const r = result;
    const lines = [
      `# AlphaScout AI — ${r.type.toUpperCase()} Analysis Report`,
      `**Target:** \`${r.target}\``,
      `**Chain:** ${r.chain ?? "N/A"}`,
      `**Risk Score:** ${r.riskScore ?? "N/A"}/100`,
      r.confidenceScore != null ? `**AI Confidence:** ${r.confidenceScore}%` : "",
      `**Analyzed:** ${new Date(r.analyzedAt).toLocaleString()}`,
      "",
      "## Executive Summary",
      r.summary,
      "",
    ];

    if (r.insights.length) {
      lines.push("## Key Findings", ...r.insights.map((i) => `- ${i}`), "");
    }
    if ((r.risks ?? []).length) {
      lines.push("## Risks", ...(r.risks ?? []).map((i) => `- ⚠ ${i}`), "");
    }
    if ((r.opportunities ?? []).length) {
      lines.push("## Opportunities", ...(r.opportunities ?? []).map((i) => `- ✓ ${i}`), "");
    }
    if ((r.recommendations ?? []).length) {
      lines.push("## Recommendations", ...(r.recommendations ?? []).map((i) => `- → ${i}`), "");
    }

    if (r.walletScan) {
      const w = r.walletScan;
      lines.push(
        "## Wallet Data",
        `- Portfolio Value: ${w.totalNetWorthUsd != null ? `$${w.totalNetWorthUsd.toLocaleString()}` : "N/A"}`,
        `- Native Balance: ${w.nativeBalance} ${w.nativeSymbol}`,
        `- Transactions: ${w.txCount}`,
        `- Wallet Age: ${w.walletAgeDays != null ? `${w.walletAgeDays} days` : "N/A"}`,
        `- Tokens: ${w.tokens.length}`,
        `- NFTs: ${w.nfts.length}`,
        `- DeFi Positions: ${w.defiPositions.length}`,
        `- Smart Money Score: ${w.smartMoneyScore ?? "N/A"}`,
        `- Wallet Health Score: ${w.walletHealthScore ?? "N/A"}`,
        `- Chains Active: ${w.chainsUsed.join(", ")}`,
        `- Data Source: ${w.dataSource}`,
        "",
      );
      if (w.tokens.length > 0) {
        lines.push("### Top Token Holdings");
        w.tokens.slice(0, 10).forEach((t) => {
          lines.push(`- **${t.symbol}** (${t.name}): ${t.balanceFormatted}${t.usdValue != null ? ` ≈ $${t.usdValue.toLocaleString()}` : ""}`);
        });
        lines.push("");
      }
    }

    if (r.tokenScan) {
      const t = r.tokenScan;
      lines.push(
        "## Token Data",
        `- Symbol: ${t.symbol} (${t.name})`,
        `- Price: ${t.priceUsd != null ? `$${t.priceUsd}` : "N/A"}`,
        `- 24h Change: ${t.priceChange24h != null ? `${t.priceChange24h > 0 ? "+" : ""}${t.priceChange24h.toFixed(2)}%` : "N/A"}`,
        `- Market Cap: ${t.marketCapUsd != null ? `$${t.marketCapUsd.toLocaleString()}` : "N/A"}`,
        `- FDV: ${t.fdvUsd != null ? `$${t.fdvUsd.toLocaleString()}` : "N/A"}`,
        `- Liquidity: ${t.liquidityUsd != null ? `$${t.liquidityUsd.toLocaleString()}` : "N/A"}`,
        `- Volume 24h: ${t.volumeH24 != null ? `$${t.volumeH24.toLocaleString()}` : "N/A"}`,
        `- Holders: ${t.holderCount?.toLocaleString() ?? "N/A"}`,
        `- Security Risk: ${t.security.overallRisk.toUpperCase()}`,
        `- Honeypot: ${t.security.isHoneypot === null ? "Unknown" : t.security.isHoneypot ? "YES ⚠" : "No ✓"}`,
        `- Buy Tax: ${t.security.buyTax ?? "?"}%`,
        `- Sell Tax: ${t.security.sellTax ?? "?"}%`,
        `- Mintable: ${t.security.isMintable === null ? "Unknown" : t.security.isMintable ? "Yes ⚠" : "No ✓"}`,
        "",
      );
    }

    if (r.contractScan) {
      const s = r.contractScan.security;
      lines.push(
        "## Contract Security",
        `- Overall Risk: ${s.overallRisk.toUpperCase()}`,
        `- Source Verified: ${s.isOpenSource == null ? "Unknown" : s.isOpenSource ? "Yes ✓" : "No ⚠"}`,
        `- Honeypot: ${s.isHoneypot == null ? "Unknown" : s.isHoneypot ? "Yes ⚠" : "No ✓"}`,
        `- Buy Tax: ${s.buyTax ?? "?"}%  |  Sell Tax: ${s.sellTax ?? "?"}%`,
        "",
      );
    }

    if (r.projectScan) {
      const p = r.projectScan;
      lines.push(
        "## Project Data",
        `- URL: ${p.url ?? "N/A"}`,
        `- Title: ${p.title ?? "N/A"}`,
        `- Description: ${p.description ?? "N/A"}`,
        `- Has Whitepaper: ${p.hasWhitepaper ? "Yes" : "No"}`,
        `- Has Audit: ${p.hasAudit ? "Yes" : "No"}`,
        `- Phishing Risk: ${p.isPhishingSite ? "YES ⚠" : "No ✓"}`,
        "",
      );
    }

    lines.push("---", `*Generated by AlphaScout AI — ${new Date().toISOString()}*`);
    return lines.filter(l => l !== undefined).join("\n");
  }

  function toJSON(): string {
    return JSON.stringify(result, null, 2);
  }

  function downloadFile(content: string, filename: string, mime: string) {
    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }

  function downloadPDF() {
    // Inject a print stylesheet and trigger browser print dialog
    const existing = document.getElementById("alphascout-print-style");
    if (!existing) {
      const style = document.createElement("style");
      style.id = "alphascout-print-style";
      style.innerHTML = `
        @media print {
          header, nav, .no-print, [data-radix-popper-content-wrapper] { display: none !important; }
          body { background: white !important; color: black !important; }
          .scanline::before { display: none !important; }
          * { box-shadow: none !important; }
        }
      `;
      document.head.appendChild(style);
    }
    window.print();
  }

  const slug = `${result.type}-${result.target.slice(0, 12)}`;

  return (
    <div className="flex flex-wrap items-center gap-2">
      <span className="text-xs font-mono text-muted-foreground/60 hidden sm:inline">Export:</span>

      <Button
        variant="outline"
        size="sm"
        className="gap-1.5 text-xs font-mono h-7 border-border/40 hover:border-primary/40"
        onClick={() => copy(toMarkdown(), "md-copy")}
      >
        {copied === "md-copy" ? <Check className="h-3 w-3 text-success" /> : <FileText className="h-3 w-3" />}
        <span className="hidden sm:inline">Markdown</span>
      </Button>

      <Button
        variant="outline"
        size="sm"
        className="gap-1.5 text-xs font-mono h-7 border-border/40 hover:border-primary/40"
        onClick={() => downloadFile(toMarkdown(), `alphascout-${slug}.md`, "text/markdown")}
      >
        <Download className="h-3 w-3" />
        <span className="hidden sm:inline">.md</span>
      </Button>

      <Button
        variant="outline"
        size="sm"
        className="gap-1.5 text-xs font-mono h-7 border-border/40 hover:border-primary/40"
        onClick={() => downloadFile(toJSON(), `alphascout-${slug}.json`, "application/json")}
      >
        {copied === "json" ? <Check className="h-3 w-3 text-success" /> : <FileJson className="h-3 w-3" />}
        <span className="hidden sm:inline">JSON</span>
      </Button>

      <Button
        variant="outline"
        size="sm"
        className="gap-1.5 text-xs font-mono h-7 border-border/40 hover:border-primary/40"
        onClick={downloadPDF}
      >
        <Printer className="h-3 w-3" />
        <span className="hidden sm:inline">PDF</span>
      </Button>

      <ShareButton result={result} />
    </div>
  );
}
